version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - localhost
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:1.0
    container_name: prometheus-nginx-exporter
    restart: always
    environment:
      GF_SECURITY_ADMIN_USER: "user"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    command:
      - --nginx.scrape-uri=http://nginx:8080/stub_status
    expose:
      - 9113
    networks:
      - localhost
    depends_on:
      - prometheus
  prometheus:
    image: prom/prometheus:v2.45.2
    user: root
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    container_name: prometheus
    restart: always
    networks:
      - localhost
    ports:
      - "9090:9090"

    # source https://grafana.com/docs/grafana/latest/installation/docker/
  grafana:
    image: grafana/grafana:10.0.10
    container_name: grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "user"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    networks:
      - localhost
    ports:
      - 3000:3000
    user: root

  client-api:
    build: ./apps/client
    working_dir: /backend/
    command: sh app.sh

  # source: https://github.com/google/cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: always
    depends_on:
      - prometheus
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    expose:
      - 8080
    networks:
      - localhost

volumes:
  nginx_conf:
  prometheus_yml:

networks:
  localhost:
    name: localhost
    external: false