version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - localhost
  grafana:
    image: grafana/grafana:10.0.10
    container_name: grafana
    restart: always
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "user"
      GF_SECURITY_ADMIN_PASSWORD: "password"
    networks:
      - localhost
    ports:
      - 3000:3000
    user: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
  influxdb:
    image: influxdb:1.4-alpine
    expose:
      - "8086"
    networks:
      - localhost
  auth-api:
    build: ./apps/auth
    working_dir: /backend/
    command: sh app.sh
    networks:
      - localhost
  incidents-api:
    build: ./apps/incidents
    working_dir: /backend/
    command: sh app.sh
    networks:
      - localhost
volumes:
  nginx_conf:

networks:
  localhost:
    name: localhost
    external: false